#!/bin/sh /etc/rc.common
START=99

start()
{
#	if [ -f /etc/crontabs/root ];then
#		cmd=`cat /etc/crontabs/root | grep loadrrd`
#		if [ -n "$cmd" ];then
#			/etc/init.d/cron restart
#			exit 0
#		fi
#	fi
#	echo "*/1 * * * * /etc/rrd/loadrrd start" >> /etc/crontabs/root

	if [ -f /etc/crontabs/root ];then
		cmd=`cat /etc/crontabs/root | grep loadrrd`
		if [ -z "$cmd" ];then
			echo "*/1 * * * * /etc/rrd/loadrrd start" >> /etc/crontabs/root
		fi

		cmd=`cat /etc/crontabs/root | grep dhcp_clientd`
		if [ -z "$cmd" ];then
			echo "*/2 * * * * /etc/dhcp_clientd start" >> /etc/crontabs/root
		fi

		cmd=`cat /etc/crontabs/root | grep qty_ctld`
		if [ -z "$cmd" ];then
			echo "*/30 * * * * /etc/qty_ctld start" >> /etc/crontabs/root
		fi

	fi
	
	/etc/init.d/cron restart
}
