#!/bin/sh

if [ $# -ne 2 ];then
	exit 0
fi
		rrdfile=/tmp/rrd/$1.rrd
		PIC=/tmp/rrd/$1_hour.png
		time=28800
		iface_name=$2
		
# only run, if no other rrdtool is running
        if [ -n "$(ps | grep rrdtool | grep -v grep)" ];then
                return
        fi

	rrdfile=/tmp/rrd/$1.rrd
	time=28800
	PIC=/tmp/rrd/$1_hour.dump
	rrdtool fetch "${rrdfile}" AVERAGE -s -"${time}" -r 900 > "${PIC}"

	
        
				
	rrdfile=/tmp/rrd/$1.rrd
	time=86400
	PIC=/tmp/rrd/$1_day.dump
	rrdtool fetch "${rrdfile}" AVERAGE -s -"${time}" -r 900 > "${PIC}"

	
	rrdfile=/tmp/rrd/$1.rrd
	time=604800
	PIC=/tmp/rrd/$1_week.dump
	rrdtool fetch "${rrdfile}" AVERAGE -s -"${time}" -r 900 > "${PIC}"

	