#!/bin/sh

echo $ACTION >> /tmp/dhcp_action.tmp

if [ "$ACTION" = add ]; then
    (
$LOG notice  "hostplug dhcp action add"
    )
fi

if [ "$ACTION" = update ]; then
    (
$LOG notice  "hostplug dhcp action update"
    )
fi

if [ "$ACTION" = remove ]; then
    (
$LOG notice  "hotplug dhc action remove"
    )
fi